// <auto-generated />
using System;
using Centric.HumanitarianAid.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HumanitarianAid.API.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class ShelterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Centric.HumanitarianAid.Business.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ShelterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ShelterId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Centric.HumanitarianAid.Business.Shelter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfPlaces")
                        .HasColumnType("int");

                    b.Property<string>("OwnerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Shelters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("19fc2719-ce34-4803-80b9-c3adb5dae760"),
                            Address = "Apple Avenue",
                            Name = "Apple",
                            NumberOfPlaces = 100,
                            OwnerEmail = "apple@apple.com",
                            OwnerName = "Mr. Apple",
                            OwnerPhone = "0712345678",
                            RegistrationDateTime = new DateTime(2022, 3, 15, 21, 2, 26, 675, DateTimeKind.Local).AddTicks(7385)
                        },
                        new
                        {
                            Id = new Guid("a177ffd4-e6d5-4a8d-8551-2371f76894c9"),
                            Address = "Cinnamon Avenue",
                            Name = "Cinnamon",
                            NumberOfPlaces = 200,
                            OwnerEmail = "cinnamon@cinnamon.com",
                            OwnerName = "Mr. Cinnamon",
                            OwnerPhone = "0712345678",
                            RegistrationDateTime = new DateTime(2022, 3, 15, 21, 2, 26, 675, DateTimeKind.Local).AddTicks(7423)
                        });
                });

            modelBuilder.Entity("Centric.HumanitarianAid.Business.Person", b =>
                {
                    b.HasOne("Centric.HumanitarianAid.Business.Shelter", null)
                        .WithMany("Persons")
                        .HasForeignKey("ShelterId");
                });

            modelBuilder.Entity("Centric.HumanitarianAid.Business.Shelter", b =>
                {
                    b.Navigation("Persons");
                });
#pragma warning restore 612, 618
        }
    }
}
